DjangoSkeleton/coffee/urls.py
from django.urls import path

from . import views

app_name = 'coffee'
urlpatterns = [
	path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),

    path('userView/', views.userView, name='userView'),
    path('userView/update-balance/', views.update_account_balance, name='update-balance'),
    path('userView/update-hours/', views.update_hours, name='update-hours'),
    path('employeeView/', views.employeeView, name='employeeView'),
    path('managerView/', views.managerView, name='managerView'),
    path('deliver-drinks/', views.deliverDrinks, name='deliverDrinks'),
    path('pay-employees/', views.payEmployees, name='pay-employees'),
    path('manageEmployees/', views.manageEmployees, name='manageEmployees'),
    path('manageEmployees/paidOrders/<int:pk>/', views.viewPaidOrders, name='paidOrders'),
    path('createEmployee/', views.createEmployee, name='createEmployee'),

    path('inventory/', views.inventory, name='inventory'),
    path('inventory/update/<int:pk>/', views.update_inventory, name="update-inventory"),

    path('drink', views.drinkProduct, name="drink"),
    path('customizeDrink/<int:pk>/', views.customizeDrink, name='customizeDrink'),

    path('userViewEmployee/<int:pk>/', views.userViewEmployee, name='userViewEmployee'),
    path('customizeDrinkEmployee/<int:pk>/<int:user>/', views.customizeDrinkEmployee, name='customizeDrinkEmployee'),
    path('customerCart/<int:pk>/', views.customerCart, name='customerCart'),

    path('drink/update-markup/', views.update_markup, name='update-markup'),
    path('drink/drink_delete/<int:pk>/', views.product_delete, name="drink_delete"),
    path('drink/drink_add/<int:pk>/', views.addDrinkProduct, name="drink_add"),
    path('drink/drink_update/<int:pk>/', views.product_update, name="drink_update"),

    path('edit-menu/', views.menuItem, name="edit-menu"),
    path('edit-menu/menu_add/', views.addMenuItem, name="menu_add"),
    path('edit-menu/menu_delete/<int:pk>/', views.deleteMenuItem, name="menu_delete"),
    path('edit-menu/menu_update/<int:pk>/', views.menu_update, name="menu_update"),

    path('shopping_cart/', views.shoppingCartView, name="shopping_cart"),

    path('notAuth.html/', views.notAuth, name='notAuth'),

]

DjangoSkeleton/mysite/urls.py
from django.contrib import admin
from django.urls import path

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    	path('admin/', admin.site.urls),
	path('', include('coffee.urls')),
]

DjangoSkeleton/coffee/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


# Create your models here.

def get_absolute_url(self):
    return reverse('my_app:my_app', kwargs={'slug': self.slug})


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_balance = models.DecimalField(max_digits=7, default=0.00, decimal_places=2) 
    hours_worked = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        newUser = instance
        if created:
            Profile.objects.create(user=newUser)
            
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def increaseBalance(self, amount):
        self.account_balance += amount
        self.save()

    def decreaseBalance(self, amount):
        self.account_balance -= amount
        self.save()

    def logHours(self, amount):
        self.hours_worked += amount
        self.save()

    def clearHours(self):
        self.hours_worked = 0
        self.save()

    def hasPaidOrders(self):
        if Order.objects.filter(profile__id=self.id, status=1):
            print("self has paid orders")
            return True
        else: 
            print("self does not have paid orders")
            return False

    def __str__(self):
        return f"\n\tUser: {self.user}"

class Order(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    totalPrice = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    status = models.IntegerField(default=0)
    # 0 : order being created by customer
    # 1 : online order has been paid for - shows up in cashier queue
    # 2 : order submitted to barista to be made - shows in cashier queue
    # 3 : order completed by barista, ready to be delivered to customer - shows in other cashier queue?
    # 4 : delivered to customer - can be deleted

    def changeStatus(self, newStatus):
        self.status = newStatus
        self.save()

    def __str__(self):
        return f"\n\t {self.profile}'s order"



class Price_Markup(models.Model):
    markup = models.IntegerField(default=0)

    def setPriceMarkup(self, newValue):
        self.markup = newValue
        self.save()

    def __str__(self):
        return f"\n\tid: {self.id} \n\tMarkup: {self.markup}"


class Inventory_Item(models.Model):
    name = models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    def gainInventory(self, value):
        self.quantity += value
        self.save()

    def useInventory(self, value):
        self.quantity -= value
        self.save()


    def __str__(self):
        return f"\n\tid: {self.id} \n\tName: {self.name} \n\tQuantity: {self.quantity} \n\tPrice: {self.price}"


class Menu_Item(models.Model):
    name = models.CharField(max_length=200)
    Ingredients = models.ManyToManyField(Inventory_Item, through='Item_Amount', related_name='inventory_items', blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True) 
    custom = models.BooleanField(default = False) # display menu items whose custom=False

    def updatePrice(self, value):
        self.price = value
        self.save()

    def __str__(self):
        return f"\n\tName: {self.name}, \n\tPrice: {self.price}"

class Item_Amount(models.Model):
    inventory_item = models.ForeignKey(Inventory_Item, related_name = 'item_amounts', on_delete=models.CASCADE)
    menu_item = models.ForeignKey(Menu_Item, related_name = 'item_amounts', on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)

    def __str__(self):
        return f"\n\t {self.amount} {self.inventory_item.name}"

    def updateAmount(self, value):
        self.amount = value
        self.save()

# # TODO: Implement a Many to Many Field for Drink Item
# class Drink_Item(models.Model):
#     name = models.CharField(max_length=200)
#     # TODO: Using a charField need to determine if there is a way to implement a dictionary in the model
#     Ingredients = models.CharField(max_length=1000)
#     price = models.DecimalField(max_digits=5, decimal_places=2)
#     order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)

#     def __str__(self):
#         return f"\n\tid: {self.id} \n\tName: {self.name} \n\tIngredients: {self.Ingredients} \n\tPrice: {self.price}"

DjangoSkeleton/coffee/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .decorators import unauthenticated_user, allowed_users
from .forms import InventoryForm, CreateUserForm, PriceMarkupForm, AccountBalanceForm, LogHoursForm, DrinkForm, MenuForm
from .models import Inventory_Item, Price_Markup, Profile, Menu_Item, Order, Item_Amount 
from decimal import Decimal

@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if request.user.groups.exists():
                group = request.user.groups.all()[0].name
                if group == 'Customer':
                    return redirect('coffee:userView')
                elif group == 'Employee':
                    return redirect('coffee:manageEmployees')
                else:
                    return redirect('coffee:managerView')
        else:
            messages.info(request, 'Username or password is incorrect')

    context = {}
    return render(request, 'coffee/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('coffee:login')


@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name='Customer')
            user.groups.add(group)

            messages.success(request, 'Account was created successfully')
            return redirect('coffee:login')

    context = {'form': form}
    return render(request, 'coffee/register.html', context)


@login_required(login_url='coffee:login')
@allowed_users(allowed_roles=['Manager'])
def createEmployee(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name='Employee')
            user.groups.add(group)
            user.profile.hours_worked = 0
            user.save()

            messages.success(request, 'Employee account was created successfully')
            return redirect('coffee:managerView')

    context = {'form': form}
    return render(request, 'coffee/createEmployee.html', context)


@login_required(login_url='coffee:login')
@allowed_users(allowed_roles=['Manager', 'Customer', 'Employee'])
def update_account_balance(request):
    user = Profile.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = AccountBalanceForm(request.POST, initial={'account_balance': 1})
        if form.is_valid():
            form.save(commit=False)
            user.increaseBalance(form.cleaned_data['account_balance'])

            return redirect('coffee:login')

    else:
        form = AccountBalanceForm(initial={'account_balance': 1})

    context = {
        'form': form,
    }
    return render(request, 'coffee/update_account_balance.html', context)


@login_required(login_url='coffee:login')
@allowed_users(allowed_roles=['Employee'])
def update_hours(request):
    user = Profile.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = LogHoursForm(request.POST, initial={'hours_worked': 1})
        if form.is_valid():
            form.save(commit=False)
            user.logHours(form.cleaned_data['hours_worked'])

            return redirect('coffee:login')

    else:
        form = LogHoursForm(initial={'hours_worked': 1})

    context = {
        'form': form,
    }
    return render(request, 'coffee/update_hours.html', context)


def getTotalHoursWorked():
    total = 0
    employees = Group.objects.get(id=3).user_set.all()
    for i in employees:
        user = Profile.objects.get(id=i.id)
        total += user.hours_worked

    return total


def clearAllHours():
    employees = Group.objects.get(id=3).user_set.all()
    for i in employees:
        user = Profile.objects.get(id=i.id)
        user.clearHours()


def payAllEmployees():
    employees = Group.objects.get(id=3).user_set.all()
    for i in employees:
        user = Profile.objects.get(id=i.id)
        user.increaseBalance(15 * user.hours_worked)


@login_required(login_url='coffee:login')
@allowed_users(allowed_roles=['Manager'])
def payEmployees(request):
    manager = Profile.objects.first()
    totalOwed = 15 * getTotalHoursWorked()

    if manager.account_balance >= totalOwed:
        if totalOwed == 0:
            messages.info(request, 'No payment neccessary at this time')
            return HttpResponseRedirect('/managerView')
        payAllEmployees()
        clearAllHours()
        manager.decreaseBalance(totalOwed)

    else:
        messages.info(request, 'Error: Insufficient funds')
        return HttpResponseRedirect('/managerView')

    return redirect('coffee:managerView')


@login_required(login_url='coffee:login')
@allowed_users(allowed_roles=['Manager', 'Customer', 'Employee'])
def shoppingCartView(request):
    current_orderq = Order.objects.filter(profile__id=request.user.id, status=0)
    if current_orderq.exists():
        current_order = current_orderq.first()

        order_total = calculateOrderTotal(current_order.id)
        context = {
                'current_order': current_order,
                'order_total': order_total
                }
    else:
        context = {'current_order': ''}

    if request.method == 'POST':
        total =  Decimal(request.POST.get('checkout'))

        user = Profile.objects.get(id=request.user.id)
        manager = Profile.objects.get(id=1)

        if user.account_balance >= total:
            ## Conflict is caused if the manager and user are the same, so Manager doesn't have to pay because this won't matter
            if user != manager:
                user.decreaseBalance(total)
                manager.increaseBalance(total)
            
            current_order.changeStatus(1)
            messages.info(request, 'Order placed successfully!')

            return redirect('coffee:login')

        else:
            messages.info(request, 'Error: Insufficient funds')

        print(total)

    return render(request, 'coffee/shopping_cart.html', context)


def calculateOrderTotal(id):
    order = Order.objects.filter(id=id).first()
    menuItems = order.menu_item_set.all()
    total = 0
    for i in menuItems:
        total += i.price

    return total


@login_required(login_url='coffee:login')
@allowed_users(allowed_roles=['Manager', 'Customer', 'Employee'])
# TODO: Need to refactor 'drink_list'
def userView(request):
    drink_list = Menu_Item.objects.filter(custom=False)
    # Menu_Item.objects.order_by('name')
    context = {'drink_list': drink_list}

    return render(request, 'coffee/userView.html', context)

@login_required(login_url='coffee:login')
@allowed_users(allowed_roles=['Manager', 'Employee'])
def userViewEmployee(request, pk):
    customerProfile = Profile.objects.get(id=pk)  
    drink_list = Menu_Item.objects.filter(custom=False)
    # Menu_Item.objects.order_by('name')
    print('customer', customerProfile)
    context = {'drink_list': drink_list, 'customer' : customerProfile}

    return render(request, 'coffee/userViewEmployee.html', context)

@login_required(login_url='coffee:login')
@allowed_users(allowed_roles=['Manager', 'Customer', 'Employee'])
def customizeDrink(request, pk):
    whos_ordering = Profile.objects.get(id=request.user.id) 

    ####### Make copy of menuItem ########
    menuItem = Menu_Item.objects.get(id=pk)
    drinkName = menuItem.name
    customDrink = Menu_Item(name = drinkName, price = menuItem.price, custom=True)
    customDrink.save()
    for ingr in menuItem.item_amounts.all():    
        Item_Amount.objects.create(menu_item=customDrink, inventory_item=ingr.inventory_item, amount = ingr.amount)
    

    ######## Make various lists for the template context ####### 
    ingred_amounts = customDrink.item_amounts.all()
    ingred_names = [dr.name for dr in customDrink.Ingredients.all()]
    
    ing_amt_dict = {}
    for ingamt in ingred_amounts:
        ing_amt_dict[ingamt.inventory_item.name.split(' ', 1)[0]] = ingamt.amount
    
    print(ing_amt_dict)

    ######## Handle POST request and etc ############
    if request.method == 'POST':
        print('submitted!')
       
        custom_ingreds = {
            'caramel' : request.POST.get('caramel'),
            'chai' : request.POST.get('chai'),
            'chocolate' : request.POST.get('chocolate'),
            'cinnamon' : request.POST.get('cinnamon'),
            'espresso' : request.POST.get('espresso'),
            'half' : request.POST.get('half'),
            'ice' : request.POST.get('ice'),
            'irish' : request.POST.get('irish'),
            'matcha' : request.POST.get('matcha'),
            'milk' : request.POST.get('milk'),
            'mocha' : request.POST.get('mocha'),
            'peppermint' : request.POST.get('peppermint'),
            'pumpkin' : request.POST.get('pumpkin'),
            'strawberry' : request.POST.get('strawberry'),
            'vanilla' : request.POST.get('vanilla'),
            'whipped' : request.POST.get('whipped'),
        }

        ########## Customize the drink based on form specifications ##########
        for ing in custom_ingreds:
            amt = int(custom_ingreds[ing])
            if amt > 0:
                inv_item = Inventory_Item.objects.get(name__startswith=ing)

DjangoSkeleton/coffee/templates/coffee/addDrinkItem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Drink</title>
</head>

<!--Reference from Models.py-->
<body>
    <label>Name</label><br>
    <input><br>

    <label>quantity</label><br>
    <input><br>

    <label>price</label><br>
    <input><br>

    <br><button type="button">Add Drink Item</button>

</body>
</html>

DjangoSkeleton/coffee/templates/coffee/customizeDrinkEmployee.html
{% extends './partials/base.html' %}
{% load static %}

{% block title %} Welcome User {% endblock %}
{% block page_heading %} Customize Your Drink {% endblock %}

{% block content %}

<div class="">
    <div class="drinkOptionsConatiner boxShadow">
        <h2 class="entry-heading">{{drink.name}}</h2>
        <h3 class="card-heading">Base Price: {{drink.price}}</h3>

        <form method="post" action="" class="">
            {% csrf_token %}
            <div class="row">
            <div class="col remSpace">
                <label for="quantity">Caramel Base :</label>
                {% if 'Caramel Base' in drinkIngreds %}
                    <input type="number" name="caramel" value={{ingredAmounts.Caramel}}>
                {% else %}
                    <input type="number" name="caramel" value="0">
                {% endif %}

                <label for="quantity">Chai Tea Base :</label>
                {% if 'Chai Tea Base' in drinkIngreds %}
                    <input type="number" name="chai" min="0" max="5" value={{ingredAmounts.Chai}}>
                {% else %}
                    <input type="number" name="chai" min="0" max="5" value="0">
                {% endif %}


                <label for="quantity">Chocolate Chips :</label>
                {% if 'Chocolate Chips' in drinkIngreds %}
                    <input type="number" name="chocolate" min="0" max="5" value={{ingredAmounts.Chocolate}}>
                {% else %}
                    <input type="number" name="chocolate" min="0" max="5" value="0">
                {% endif %}


                <label for="quantity">Cinnamon :</label>
                {% if 'Cinnamon' in drinkIngreds %}
                    <input type="number" name="cinnamon" min="0" max="5" value={{ingredAmounts.Cinnamon}}>
                {% else %}
                    <input type="number" name="cinnamon" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Espresso Shot :</label>
                {% if 'Espresso Shot' in drinkIngreds %}
                    <input type="number" name="espresso" min="0" max="5" value={{ingredAmounts.Espresso}}>
                {% else %}
                    <input type="number" name="espresso" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Half and Half :</label>
                {% if 'Half and Half' in drinkIngreds %}
                    <input type="number" name="half" min="0" max="5" value={{ingredAmounts.Half}}>
                {% else %}
                    <input type="number" name="half" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Ice :</label>
                {% if 'Ice' in drinkIngreds %}
                    <input type="number" name="ice" min="0" max="5" value={{ingredAmounts.Ice}}>
                {% else %}
                    <input type="number" name="ice" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Irish Cream Syrup :</label>
                {% if 'Irish Cream Syrup' in drinkIngreds %}
                    <input type="number" name="irish" min="0" max="5" value={{ingredAmounts.Irish}}>
                {% else %}
                    <input type="number" name="irish" min="0" max="5" value="0">
                {% endif %}
            </div>

            <div class="col remSpace">
                <label for="quantity">Matcha Powder :</label>
                {% if 'Matcha Powder' in drinkIngreds %}
                    <input type="number" name="matcha" min="0" max="5" value={{ingredAmounts.Matcha}}>
                {% else %}
                    <input type="number" name="matcha" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Milk :</label>
                {% if 'Milk' in drinkIngreds %}
                    <input type="number" name="milk" min="0" max="5" value={{ingredAmounts.Milk}}>
                {% else %}
                    <input type="number" name="milk" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Mocha Base :</label>
                {% if 'Mocha Base' in drinkIngreds %}
                    <input type="number" name="mocha" min="0" max="5" value={{ingredAmounts.Mocha}}>
                {% else %}
                    <input type="number" name="mocha" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Peppermint :</label>
                {% if 'Peppermint' in drinkIngreds %}
                    <input type="number" name="peppermint" min="0" max="5" value={{ingredAmounts.Peppermint}}>
                {% else %}
                    <input type="number" name="peppermint" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Pumpkin Spice Syrup :</label>
                {% if 'Pumpkin Spice Syrup' in drinkIngreds %}
                    <input type="number" name="pumpkin" min="0" max="5" value={{ingredAmounts.Pumpkin}}>
                {% else %}
                    <input type="number" name="pumpkin" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Strawberry Puree :</label>
                {% if 'Strawberry Puree' in drinkIngreds %}
                    <input type="number" name="strawberry" min="0" max="5" value={{ingredAmounts.Strawberry}}>
                {% else %}
                    <input type="number" name="strawberry" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Vanilla Base :</label>
                {% if 'Vanilla Base' in drinkIngreds %}
                    <input type="number" name="vanilla" min="0" max="5" value={{ingredAmounts.Vanilla}}>
                {% else %}
                    <input type="number" name="vanilla" min="0" max="5" value="0">
                {% endif %}

                <label for="quantity">Whipped Cream :</label>
                {% if 'Whipped Cream' in drinkIngreds %}
                    <input type="number" name="whipped" min="0" max="5" value={{ingredAmounts.Whipped}}>
                {% else %}
                    <input type="number" name="whipped" min="0" max="5" value="0">
                {% endif %}
            </div>
            </div>

            <div class="col remSpace autoMargin">
                <input class="btn autoMargin" type="submit" value="Add to Order">
            </div>
        </form>

            <div class="col">
                <a class="btn btn-info remSpace autoMargin" href="{% url 'coffee:userViewEmployee' customer.user.id %}">Cancel</a> <!-- delete the drink if this is clicked -->
            </div>

    </div>
</div>

{% endblock %}

DjangoSkeleton/coffee/templates/coffee/drink_update.html
{% extends './partials/base.html' %}

{% block title %} Update Drink {% endblock %}
{% block page_heading %} Update Drink {% endblock %}

{% block content %}
<div class="table">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="border bg-white p-3">
                <h3>Edit Item</h3>
                <hr>

                <form method ="POST">
                    {% csrf_token %}
                    <div class="inputStyling main-section">{{ form }}</div>
                    <a class="btn btn-secondary" href="{% url 'coffee:drink' %}">Cancel</a>
                    <input class ="btn btn-info" type ="submit" value="Update">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

DjangoSkeleton/coffee/templates/coffee/login.html
{% extends './partials/base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
<section class="data-entry-form">

    <h1 class="sign-in-h1">Sign In</h2>
    <form method="POST" action=""> 
        {% csrf_token %}
        <label for="fname">Username:</label><br>
        <input type="text" id="fname" name="username" ><br>
        <label for="lname">Password:</label><br>
        <input type="password" id="lname" name="password" class="form-control" ><br><br>
        <input type="submit" value="Login">
    </form> 
    <div class="register_link">
        Don't have an account yet? <a href="{% url 'coffee:register' %}" >Register</a>
    </div>
</section>

<script>
    function alertMessage(message) {
      alert(message);
    }
</script>


{% for message in messages %}
    <script>alertMessage('{{message}}')</script>
{% endfor %}

{% endblock %}

DjangoSkeleton/coffee/templates/coffee/managerView.html
{% extends './partials/base.html' %}

{% block title %} Manager View {% endblock %}
{% block page_heading %} Let's Cook {% endblock %}

{% block content %}
<div class="row-container">

  <div class="manage-edit">
      <a class="boxShadow" href="{% url 'coffee:inventory' %}">Manage Inventory</a>
    <a class="boxShadow" href="{% url 'coffee:edit-menu' %}">Edit Menu</a>
  </div>

  <div class="manage-employees">
    <a class="boxShadow" href="{% url 'coffee:createEmployee' %}">Add New Employee</a>
    <a class="boxShadow" href="{% url 'coffee:pay-employees' %}">Pay Employees</a>
  </div>
  
</div>
{% endblock %}

DjangoSkeleton/coffee/templates/coffee/menuItem.html
{% extends './partials/base.html' %}

{% block title %} Menu Items {% endblock %}
{% block page_heading %} Manage Menu Items {% endblock %}

{% block content %}

<div class="col">
    <h3 class="column-heading">Price markup: {{ markup.markup }}%</h3>
</div>
<nav>

    <ul class="button-links">
        <li><a class="btn" href="{% url 'coffee:update-markup' %}">Edit</a></li>
        <li><a class="btn" href="{% url 'coffee:menu_add' %}">Create Drink</a></li>
    </ul>
</nav>

{% if menu_list %}
<table class="table" style="border-color:#ccb593;">

    <thead>
    <tr>
        <th scope="col">Drink</th>
        <th scope="col">Price</th>
        <th scope="col">Ingredient</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for item in menu_list %}
    <tr>
        <th scope="row">{{ item.name }}</th>
        <td>{{ item.price }}</td>
        <td>
            <div class="row">
                <div class="col-md-6">
                    <p>

                        {% for test in item.item_amounts.all %}
                            {{ test.amount }} {{ test.inventory_item.name }},
                        {% endfor %}
                    </p>
                </div>
                <div class="col-md-6">
                    <a class="btn btn-danger" href="{% url 'coffee:menu_delete' item.id %}">-</a>
                    <a class="btn btn-dark" href="{% url 'coffee:menu_update' item.id %}">Edit</a>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h5>No inventory items in database</h5>
{% endif %}

{% endblock %}

DjangoSkeleton/coffee/templates/coffee/userViewEmployee.html
{% extends './partials/base.html' %}
{% load static %}

{% block title %} Welcome User {% endblock %}
{% block page_heading %} Start New Order  
<a class="boxShadow" href="{% url 'coffee:customerCart' customer.user.id %}">Cart</a> 
{% endblock %}

{% block content %}


{% for item in drink_list %}
<div class="order">
    <a class="order-link" href="{% url 'coffee:customizeDrinkEmployee' item.id customer.user.id %}">
        <div class="image">
            <img src="{% static 'coffee/media/aFrap.jpeg' %}">
        </div>
        <div class="order-description">
            <h2>{{ item.name }}</h2>
            <p>
                {% for test in item.Ingredients.all %}
                {{ test.name }},
                {% endfor %}
            </p>
        </div>
        <div class="price-of-order">
            <h1>${{ item.price }}</h1>
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}